---
title: plynty website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  assets:
    title: assets
    output: true
  authors:
    title: authors
    output: true
  formats:
    title: formats
    output: true
  products:
    title: products
    output: true
  sections:
    title: sections
    output: true
  support-articles:
    title: support articles
    output: true
defaults:
- scope:
    path: ''
    type: sections
  values:
    format: ''
    page: ''
    image: ''
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/post/:title.html"
    asset: ''
    image: ''
    author: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
email: support@plynty.com
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
assets:
  compress:
    css: true
    js: true
excerpt_separator: "<!--more-->"
gems:
- jekyll-textile-converter
